### ISSUE TITLE
Fix indexing issue with sample plots

### ISSUE THREAD

**Issue by nsfabina** [pgbrodrick/bfg-nets#90]
This error occurred when I was trying to plot a set of very few samples. I'm guessing that we need to check that we're not requesting more sample plots than we  have available samples, as the reporting config would have allowed for that possibility. This should be relatively simple.

```
Traceback (most recent call last):
  File "run_classification.py", line 74, in <module>
    run_classification(**args)
  File "run_classification.py", line 62, in run_classification
    raise error_
  File "run_classification.py", line 51, in run_classification
    reporter.create_model_report()
  File "/home/nfabina/bfg-nets/bfgn/reporting/reports.py", line 56, in create_model_report
    self._create_model_report_for_sequence(sampled, pdf)
  File "/home/nfabina/bfg-nets/bfgn/reporting/reports.py", line 66, in _create_model_report_for_sequence
    self._add_figures(self.plot_samples(sampled), pdf)
  File "/home/nfabina/bfg-nets/bfgn/reporting/reports.py", line 121, in plot_samples
    max_responses_per_page=max_responses_per_page
  File "/home/nfabina/bfg-nets/bfgn/reporting/visualizations/samples.py", line 25, in plot_classification_samples
    sample_type=LABEL_CLASSIFICATION
  File "/home/nfabina/bfg-nets/bfgn/reporting/visualizations/samples.py", line 71, in _plot_samples
    sample_plotter(sampled, idx_sample, num_features, num_responses, sample_axes)
  File "/home/nfabina/bfg-nets/bfgn/reporting/visualizations/samples.py", line 89, in _plot_classification_sample
    sampled, idx_sample, idx_feature, sample_axes.__next__(), idx_sample == 0, idx_feature == 0)
  File "/home/nfabina/bfg-nets/bfgn/reporting/visualizations/subplots.py", line 38, in plot_raw_features
    _plot_sample_attribute(sampled, idx_sample, idx_feature, 'raw_features', ax, add_xlabel, add_ylabel)
  File "/home/nfabina/bfg-nets/bfgn/reporting/visualizations/subplots.py", line 132, in _plot_sample_attribute
    attribute_values = getattr(sampled, attribute_name)[idx_sample, :, :, idx_axis]
  File "/home/nfabina/miniconda3/envs/asu/lib/python3.7/site-packages/numpy/core/memmap.py", line 331, in __getitem__
    res = super(memmap, self).__getitem__(index)
IndexError: index 10 is out of bounds for axis 0 with size 10
```

**Comment by nsfabina** [comment]
Fixed in latest
